// fall-euaiact · comply.mjs — the estate's compliance map. One declaration of what a build does in, one map out:
// its EU AI Act role and risk tier, the dates that apply, and every GDPR / UK GDPR / EU AI Act duty that applies to
// it on its stack — each duty quoted from the primary text, linked, and dated (law/law.json).
//
// Every estate build carries a map generated by this kernel (tools/comply-build.mjs), and konomify's basis gate
// refuses a build without a current one. The duties and their per-stack status come from fallfloor-enterprise's
// obligations kernel, generalised: a build declares facts (does it run an AI system, touch personal data, talk to
// the public, make significant decisions, fall under Annex III), and the kernel does the mapping. Nothing is typed
// twice: a date, a quote or a status lives once, in law/law.json.
//
// PURE and TOTAL: no DOM, no I/O, no clock (the caller passes asOf), no throw on garbage.

const isStr = (v) => typeof v === 'string' && v.length > 0;
const isObj = (v) => typeof v === 'object' && v !== null && !Array.isArray(v);
const isBool = (v) => v === true || v === false;
const fail = (why) => ({ ok: false, why });
const DATE = /^\d{4}-\d{2}-\d{2}$/;
const HTTPS = /^https:\/\/\S+$/;

export const DEPLOYMENTS = ['local', 'cloud', 'saas'];
export const STATUSES = ['removed', 'eased', 'yours', 'shared', 'unchanged'];
export const CONDITIONS = ['always', 'aiSystem', 'personalData', 'interactsWithPublic', 'generatesContent', 'significantDecision', 'highRisk', 'creditScoring', 'prohibited', 'euOutput', 'providerAbroad', 'trainsOnPersonalData'];
export const AI_KINDS = ['none', 'narrow', 'generative'];
export const BUILT_BY = ['self', 'vendor'];
export const ANNEX_III = ['biometrics', 'critical-infrastructure', 'education', 'employment', 'essential-services', 'creditworthiness', 'law-enforcement', 'migration', 'justice'];
export const TIERS = ['prohibited', 'high', 'limited', 'minimal'];

// A duty applies when every one of its conditions holds. One condition or a list (all of them).
const holds = (appliesIf, f) => (Array.isArray(appliesIf) ? appliesIf : [appliesIf]).every((c) => f[c] === true);
const knownConditions = (appliesIf) => {
  const list = Array.isArray(appliesIf) ? appliesIf : [appliesIf];
  return list.length > 0 && list.every((c) => CONDITIONS.includes(c));
};

/** obligations(workload, deployment, duties, ctx) — which duties apply to a workload on a stack, and what that stack
 *  does to each. workload: { flags: {condition: true, ...} }; ctx: { asOf: 'YYYY-MM-DD', providerAbroad: bool }. */
export function obligations(workload, deployment, duties, ctx) {
  if (!isObj(workload) || !isObj(workload.flags)) return fail('a workload with flags');
  if (!DEPLOYMENTS.includes(deployment)) return fail('deployment must be local, cloud or saas');
  if (!Array.isArray(duties)) return fail('duties must be a list');
  if (!isObj(ctx) || !DATE.test(ctx.asOf || '')) return fail('ctx.asOf must be a date');
  const f = { ...workload.flags, always: true, providerAbroad: ctx.providerAbroad === true };   // shown on every stack, so the local column can say 'removed'
  const items = [];
  const counts = Object.fromEntries(STATUSES.map((s) => [s, 0]));
  for (const d of duties) {
    if (!isObj(d) || !isStr(d.id) || !knownConditions(d.appliesIf) || !isObj(d.status) || !STATUSES.includes(d.status[deployment]) || !DATE.test(d.from || '') || !HTTPS.test(d.url || '') || !DATE.test(d.checked || '')) return fail('duty ' + String(d && d.id) + ' is malformed (condition, status per stack, from, https url, checked)');
    if (!holds(d.appliesIf, f)) continue;
    const status = d.status[deployment];
    counts[status]++;
    items.push({ id: d.id, regime: d.regime, ref: d.ref, title: d.title, status, inForce: d.from <= ctx.asOf, from: d.from, note: isObj(d.note) ? d.note[deployment] : '', quote: d.quote, url: d.url, checked: d.checked });
  }
  const role = deployment === 'saas' ? 'deployer (the vendor is the provider of its assistant)' : 'provider and deployer (the company puts its own AI system into service)';
  return { ok: true, deployment, role, items, counts, applying: items.length };
}

/** declare(d) — check a build's declaration and turn it into the facts the duties are conditioned on.
 *  Required: declared (true), system, ai ('none' | 'narrow' | 'generative'), builtBy ('self' | 'vendor'),
 *  personalData, euOutput (booleans), deployment ('local' | 'cloud' | 'saas').
 *  Optional (false / null when absent): interactsWithPublic, generatesContent, significantDecision, providerAbroad,
 *  trainsOnPersonalData (booleans); annexIII (one of ANNEX_III); prohibited (the Art 5 point, e.g. '5(1)(c)'). */
export function declare(d) {
  if (!isObj(d)) return fail('a declaration object (compliance.decl.json)');
  if (d.declared !== true) return fail('not declared yet: set "declared": true once every fact below is true of this build');
  if (!isStr(d.system)) return fail('system: one line saying what the build does');
  if (!AI_KINDS.includes(d.ai)) return fail('ai must be none, narrow or generative');
  if (!BUILT_BY.includes(d.builtBy)) return fail('builtBy must be self or vendor');
  if (!DEPLOYMENTS.includes(d.deployment)) return fail('deployment must be local, cloud or saas');
  for (const k of ['personalData', 'euOutput']) if (!isBool(d[k])) return fail(k + ' must be true or false');
  const opt = {};
  for (const k of ['interactsWithPublic', 'generatesContent', 'significantDecision', 'providerAbroad', 'trainsOnPersonalData']) {
    if (d[k] !== undefined && !isBool(d[k])) return fail(k + ' must be true or false when given');
    opt[k] = d[k] === true;
  }
  const annexIII = d.annexIII === undefined ? null : d.annexIII;
  if (annexIII !== null && !ANNEX_III.includes(annexIII)) return fail('annexIII must be one of ' + ANNEX_III.join(', ') + ', or null');
  const prohibited = d.prohibited === undefined ? null : d.prohibited;
  if (prohibited !== null && !/^5\(1\)\([a-h]\)$/.test(prohibited)) return fail('prohibited must name the Art 5(1) point, e.g. 5(1)(c), or be null');
  const ai = d.ai !== 'none';
  if (!ai && (opt.interactsWithPublic || opt.generatesContent || annexIII !== null || prohibited !== null)) return fail('an AI Act use (Art 50, Annex III, Art 5) needs an AI system: ai cannot be none');
  if (d.deployment === 'local' && opt.providerAbroad) return fail('providerAbroad cannot be true when nothing leaves the building (deployment local)');
  if (opt.trainsOnPersonalData && !d.personalData) return fail('trainsOnPersonalData needs personalData');
  const flags = {
    aiSystem: ai, personalData: d.personalData, interactsWithPublic: opt.interactsWithPublic, generatesContent: opt.generatesContent,
    significantDecision: opt.significantDecision, highRisk: annexIII !== null, creditScoring: annexIII === 'creditworthiness',
    prohibited: prohibited !== null, euOutput: d.euOutput, providerAbroad: opt.providerAbroad, trainsOnPersonalData: opt.trainsOnPersonalData,
  };
  return { ok: true, flags, system: d.system, ai: d.ai, builtBy: d.builtBy, deployment: d.deployment, annexIII, prohibited };
}

/** tierOf(flags) — the AI Act risk tier: prohibited (Art 5) > high (Annex III) > limited (Art 50) > minimal.
 *  null when there is no AI system. */
export function tierOf(flags) {
  if (!isObj(flags) || flags.aiSystem !== true) return null;
  if (flags.prohibited === true) return 'prohibited';
  if (flags.highRisk === true) return 'high';
  if (flags.interactsWithPublic === true || flags.generatesContent === true) return 'limited';
  return 'minimal';
}

/** complianceMap(decl, law, asOf) — the whole map for one build: the AI Act position, whether GDPR is engaged, every
 *  duty that applies on its stack (quoted, linked, dated, in force or from when), the dates, and anything that
 *  blocks shipping (a prohibited practice). law: { checked, duties: [...], dates: [...] } from law/law.json. */
export function complianceMap(decl, law, asOf) {
  const d = declare(decl);
  if (!d.ok) return d;
  if (!isObj(law) || !Array.isArray(law.duties) || !Array.isArray(law.dates) || !DATE.test(law.checked || '')) return fail('law must carry checked, duties and dates');
  if (!DATE.test(asOf || '')) return fail('asOf must be a date');
  const ob = obligations({ flags: d.flags }, d.deployment, law.duties, { asOf, providerAbroad: d.flags.providerAbroad });
  if (!ob.ok) return ob;
  const tier = tierOf(d.flags);
  const aiAct = !d.flags.aiSystem
    ? { applies: false, why: 'No AI system (Art 3(1)): the build runs no model that infers its outputs, so the AI Act places no duty on it.' }
    : !d.flags.euOutput
      ? { applies: false, why: 'No output used in the EU and nothing placed on the EU market (Art 2(1)): outside the AI Act\'s scope.', tier }
      : { applies: true, role: d.builtBy === 'self' ? 'provider (Art 3(3)) — it builds the AI system and puts it into service under its own name' : 'deployer (Art 3(4)) — it uses an AI system under its authority', tier };
  const gdpr = d.flags.personalData
    ? { applies: true, why: 'The build processes personal data: GDPR / UK GDPR duties apply to whoever controls it.' }
    : { applies: false, why: 'No personal data is processed, so no GDPR / UK GDPR duty arises from the build.' };
  const blocking = d.flags.prohibited && d.flags.euOutput ? ['A prohibited AI practice (Art ' + d.prohibited + '): it may not be placed on the market, put into service or used in the EU.'] : [];
  return {
    ok: true, v: 1, system: d.system, asOf, lawChecked: law.checked, ai: d.ai, deployment: d.deployment, annexIII: d.annexIII,
    aiAct, gdpr, items: ob.items, counts: ob.counts, applying: ob.applying,
    inForce: ob.items.filter((i) => i.inForce).length, upcoming: ob.items.filter((i) => !i.inForce).map((i) => ({ id: i.id, from: i.from })),
    blocking,
  };
}
