#!/usr/bin/env node
// tools/pull-basis.mjs — this design's basis, pulled from the estate, never typed:
//   · prices.lock.json + sources/prices.json — from fallstack's price registry (every price the cost case uses)
//   · sources/organs.json — the SaaS each function rents, the estate organ that replaces it and its rung on the
//     ladder, from fallstack's organ map and GitHub evidence, run through fallstack's own gated kernel
//   · comply.mjs + comply.test.mjs + law/law.json — the estate compliance kernel, its tests and the verified law,
//     verbatim from fall-euaiact (the tests come too, so this repository's mutation gate proves the copy it runs)
//
//   node tools/pull-basis.mjs [--from <dir with fallstack and fall-euaiact>]            write them
//   node tools/pull-basis.mjs --check [--from <dir>]                                      exit 1 on any difference
// CI runs --check against both repositories cloned at pinned commits.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const argv = process.argv.slice(2);
const FROM = resolve(argv.includes('--from') ? argv[argv.indexOf('--from') + 1] : join(ROOT, '..'));
const CHECK = argv.includes('--check');
const STACK = join(FROM, 'fallstack'), EUAIACT = join(FROM, 'fall-euaiact');
const read = (p) => readFileSync(p, 'utf8').replace(/\r\n/g, '\n');
const json = (p) => JSON.parse(read(p));

// the registry ids this cost case uses, in the order the page lists them
export const IDS = [
  'm365-copilot', 'chatgpt-business', 'claude-enterprise', 'claude-team',
  'gpt-5-nano', 'gpt-5-mini', 'gemini-3.1-flash-lite', 'claude-haiku-4.5', 'claude-sonnet-5',
  'salesforce-pro-suite', 'dynamics-365-finance', 'dynamics-365-human-resources',
  'uk-vat', 'fx-gbp-usd', 'desnz-electricity-nondomestic', 'intel-i7-1255u-power', 'ons-ashe-2025-it-salaries',
  'ons-cpi', 'uk-national-living-wage', 'ons-ashe-2025-median-hourly', 'boe-inflation-target',
  'microsoft-365-2026-rise', 'salesforce-2025-rise',
];
const SINGLE = {
  vatRate: 'uk-vat', fx: 'fx-gbp-usd', electricity: 'desnz-electricity-nondomestic', laptopPower: 'intel-i7-1255u-power',
  salaries: 'ons-ashe-2025-it-salaries', cpi: 'ons-cpi', wage: 'uk-national-living-wage', wageMedian: 'ons-ashe-2025-median-hourly',
  cpiTarget: 'boe-inflation-target', risingCost: 'microsoft-365-2026-rise', saasRise: 'salesforce-2025-rise',
};

const P = await import(pathToFileURL(join(STACK, 'prices.mjs')).href);
const S = await import(pathToFileURL(join(STACK, 'stack.mjs')).href);
const registry = json(join(STACK, 'registry', 'prices.json'));
const organMap = json(join(STACK, 'registry', 'organs.json'));
const evidence = json(join(STACK, 'registry', 'tier-evidence.json'));

const pulled = P.pull(registry, IDS);
if (!pulled.ok) { console.error('NOT PULLED: ' + pulled.why); process.exit(1); }
const lock = pulled.lock;
const byId = new Map(lock.entries.map((e) => [e.id, e]));
const listed = (kind) => lock.entries.filter((e) => e.kind === kind).map(({ kind: _k, ...rest }) => ({ ...rest, registry: rest.id }));
const single = (id) => { const { id: _i, kind: _k, ...rest } = byId.get(id); return { ...rest, registry: id }; };
const prices = {
  _rule: 'GENERATED by tools/pull-basis.mjs from fallstack\'s price registry (prices.lock.json) — never edit by hand. Every figure is the registry\'s: quoted as its source states it, linked, dated. "registry" names the entry each one came from.',
  checked: lock.entries.map((e) => e.checked).sort().pop(),
  seats: listed('seat'), api: listed('api'), saas: listed('saas'),
  ...Object.fromEntries(Object.entries(SINGLE).map(([k, id]) => [k, single(id)])),
};
const organs = {
  _rule: 'GENERATED by tools/pull-basis.mjs from fallstack\'s organ map and its GitHub evidence, through fallstack\'s gated kernel (stack.mjs) — never edit by hand. The rung on the ladder is computed from what GitHub\'s runners did.',
  from: 'https://github.com/sjgant80-hub/fallstack', scanned: evidence.scanned,
  functions: organMap.functions.map((f) => {
    const r = S.replacement(f.fn, organMap, evidence.organs);
    const { ok: _o, ...rest } = r;
    return { ...rest, label: f.label, organName: f.organName || null };
  }),
};
const files = {
  'prices.lock.json': JSON.stringify({ ...lock, pulledFrom: 'https://github.com/sjgant80-hub/fallstack/blob/main/registry/prices.json' }, null, 1) + '\n',
  'sources/prices.json': JSON.stringify(prices, null, 1) + '\n',
  'sources/organs.json': JSON.stringify(organs, null, 1) + '\n',
  'comply.mjs': read(join(EUAIACT, 'comply.mjs')),
  'comply.test.mjs': read(join(EUAIACT, 'comply.test.mjs')),
  'law/law.json': read(join(EUAIACT, 'law', 'law.json')),
};
if (CHECK) {
  const off = Object.entries(files).filter(([f, text]) => !existsSync(join(ROOT, f)) || read(join(ROOT, f)) !== text).map(([f]) => f);
  if (off.length) { console.error('BASIS DRIFT — these do not match fallstack / fall-euaiact at ' + FROM + ':\n  ' + off.join('\n  ')); process.exit(1); }
  console.log('basis matches the estate: ' + lock.entries.length + ' registry entries, ' + organs.functions.length + ' functions, comply.mjs and the law verbatim');
} else {
  for (const [f, text] of Object.entries(files)) writeFileSync(join(ROOT, f), text);
  console.log('pulled: ' + lock.entries.length + ' registry entries · ' + organs.functions.length + ' functions (' + organs.functions.filter((f) => f.replaced).map((f) => f.fn + ' → ' + f.organ + ' ' + f.tier).join(', ') + ') · comply.mjs · law (' + json(join(EUAIACT, 'law', 'law.json')).duties.length + ' duties)');
}
